# Generated by Django 5.0.6 on 2024-06-02 15:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0002_alter_lesson_course"),
        ("users", "0002_alter_user_options_alter_user_avatar"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Укажите дату оплаты",
                        verbose_name="дата оплаты",
                    ),
                ),
                (
                    "summ",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Укажите оплаченную сумму",
                        max_digits=9,
                        verbose_name="оплаченная сумма",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[("Наличными", "Наличными"), ("Картой", "Картой")],
                        help_text="Выберите способ оплаты",
                        verbose_name="Способ оплаты",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        help_text="Укажите курс",
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="payment",
                        to="lms.course",
                        verbose_name="курс",
                    ),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        blank=True,
                        help_text="Укажите урок",
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="payment",
                        to="lms.lesson",
                        verbose_name="урок",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Укажите пользователя",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Платёж",
                "verbose_name_plural": "Платежи",
            },
        ),
    ]
