# Generated by Django 5.0.6 on 2024-06-11 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0005_alter_lesson_course"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="course",
            options={
                "ordering": ("pk",),
                "verbose_name": "Курс",
                "verbose_name_plural": "Курсы",
            },
        ),
        migrations.AlterModelOptions(
            name="lesson",
            options={
                "ordering": ("pk",),
                "verbose_name": "Урок",
                "verbose_name_plural": "Уроки",
            },
        ),
    ]
