# Generated by Django 5.0.6 on 2024-06-12 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0006_alter_course_options_alter_lesson_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="price",
            field=models.IntegerField(
                default=0, help_text="Укажите цену курса", verbose_name="Цена курса"
            ),
        ),
    ]
