# Generated by Django 5.0.6 on 2024-06-12 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0007_course_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="payment_link",
            field=models.URLField(
                blank=True,
                help_text="Укажите ссылку на оплату",
                max_length=400,
                null=True,
                verbose_name="ссылка на оплату",
            ),
        ),
    ]
